font_size = 30
show_view = [ [ "Demo", false,], [ "实时捕获", false,], [ "打开 pcap", true,], [ "统计", true,],]
windows_pos = [ 255, 125,]
windows_size = [ 2139, 1271,]
selected = 3
theme = "light"
tshark_path = "./tshark/tshark.exe"

[setting]
auto_scroll = false
