font_size = 30
show_view = [ [ "Demo", true,], [ "实时捕获", true,], [ "打开 pcap", true,], [ "统计", false,],]
windows_pos = [ -182, 195,]
windows_size = [ 2560, 1370,]
selected = 3
theme = "light"
tshark_path = "./tshark/tshark.exe"

[setting]
auto_scroll = false
