font_size = 30
show_view = [ [ "Demo", false,], [ "实时捕获", true,], [ "打开 pcap", true,], [ "统计", false,],]
windows_pos = [ 133, 124,]
windows_size = [ 2240, 1292,]
selected = 3
theme = "light"
tshark_path = "./tshark/tshark.exe"

[setting]
auto_scroll = false
